-- Creates a log table for completed roadmap items
create table if not exists roadmap_item_log (
  id bigint generated by default as identity primary key,
  item_id bigint references roadmap_items(id),
  completed_at timestamptz default timezone('utc', now())
);

-- Function that marks a roadmap item as done and logs completion
create or replace function complete_roadmap_task(
  item_id bigint,
  title text,
  details text,
  type roadmap_item_type,
  priority int
) returns void as $$
begin
  update roadmap_items
    set title = coalesce(complete_roadmap_task.title, roadmap_items.title),
        details = complete_roadmap_task.details,
        type = complete_roadmap_task.type,
        priority = complete_roadmap_task.priority,
        status = 'completed'
    where id = complete_roadmap_task.item_id;

  insert into roadmap_item_log(item_id) values (complete_roadmap_task.item_id);
end;
$$ language plpgsql;
