-- Creates a log table for completed roadmap items
create table if not exists roadmap_item_log (
  id bigint generated by default as identity primary key,
  item_id bigint references roadmap_items(id),
  completed_at timestamptz default timezone('utc', now())
);

-- Canonical function name is complete_task; legacy name complete_roadmap_task is retained for compatibility.
create or replace function complete_task(
  task_id bigint,
  title text,
  description text,
  priority int
) returns void as $$
begin
  update roadmap_items
    set title = coalesce(complete_task.title, roadmap_items.title),
        content = complete_task.description,
        priority = complete_task.priority,
        type = 'done'
    where id = complete_task.task_id;

  insert into roadmap_item_log(item_id) values (complete_task.task_id);
end;
$$ language plpgsql;
