name: agent-normalize-roadmap
on:
  schedule: [{ cron: "22 3 * * *" }]
  workflow_dispatch:
jobs:
  normalize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - run: npm ci --no-audit --no-fund
      - run: npm run build
      - run: node dist/cli.js normalize-roadmap
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
          TARGET_REPO: ${{ secrets.TARGET_REPO }}
