name: ai-dev-agent
on:
  schedule:
    - cron: "*/15 * * * *"   # implement
    - cron: "0 */6 * * *"    # ingest-logs (every 6h)
    - cron: "7 4 * * *"      # review-repo (04:07 UTC)
    - cron: "12 4 * * *"     # synthesize-tasks (04:12 UTC)
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: ai-agent-${{ github.ref }}
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        step: [ "ingest-logs", "review-repo", "synthesize-tasks", "implement" ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - run: npm ci
      - run: npm run build
      - run: node dist/cli.js ${{ matrix.step }}
        env:
          GH_USERNAME: ${{ secrets.GH_USERNAME }}
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
          TARGET_REPO: ${{ secrets.TARGET_REPO }}
          TARGET_DIR: ${{ secrets.TARGET_DIR }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_TEAM_ID: ${{ secrets.VERCEL_TEAM_ID }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_MODEL: ${{ secrets.OPENAI_MODEL }}
          AI_BOT_WRITE_MODE: commit
          DRY_RUN: "0"
          ALLOW_PATHS: ""
