name: ci

on:
  push:
    branches: [main]
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run build

      - name: Run orchestrator
        run: node dist/orchestrator.js
        env:
          TARGET_OWNER: ${{ secrets.TARGET_OWNER }}
          TARGET_REPO: ${{ secrets.TARGET_REPO }}

      # Required secrets for orchestrator:
      #   - TARGET_OWNER (e.g. "basstian-ai")
      #   - TARGET_REPO (e.g. "simple-pim-1754492683911")

      - name: Run tests
        run: npm test
